apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
  namespace: voting-app
type: kubernetes.io/dockerconfigjson
data:
  # This will be created using: kubectl create secret docker-registry acr-secret
  # See deployment instructions for details
  .dockerconfigjson: ""

