apiVersion: v1
kind: Secret
metadata:
  name: voting-app-secrets
  namespace: voting-app
type: Opaque
stringData:
  # IMPORTANT: In production, use Azure Key Vault or generate secure passwords
  # For now, using base64 encoded values (postgres/postgres)
  # To generate: echo -n 'your-password' | base64
  postgres-password: postgres
  postgres-connection-string: "Server=postgres;Username=postgres;Password=postgres;Database=postgres;"
  postgres-url: "postgres://postgres:postgres@postgres/postgres"

